### ISSUE TITLE
Icon's width is not the same as that defined in css

### ISSUE THREAD

**Issue by khiav223577** [websemantics/Image-Select#42]
In css, the icon width is set to `18px`
```css
.chose-image-small {
	width:18px;
	max-height:18px;
	vertical-align: middle;
	margin: -3px 0 0 0;
	padding: 0 3px 0 0;
}
```
But actually, it is `15px`
![2017-05-18 5 55 56](https://cloud.githubusercontent.com/assets/4011729/26196990/480b1cc8-3bf3-11e7-994d-480181af5f91.png)

Is this expected result?

---

change
```css
.chose-image-small {
	 margin: -3px 0 0 0;
	padding: 0 3px 0 0;
}
```
to 
```css
.chose-image-small {
	margin: -3px 3px 0 0;
}
```
will fix this issue
